export const SiteTheme = {
  size: {
    xs: "0",
    sm: "576px",
    md: "768px",
    lg: "992px",
    xl: "1200px",
    xxl: "1400px",
    mxw: "530px",
    mmw: "767px",
  },
  device: {
    xs: `(min-width: 0)`,
    xsMin: `(min-width: 360px)`,
    xsM: `(min-width: 390px)`,
    sm: `(min-width: 567px)`,
    smMax: `(max-width: 767px)`,
    md: `(min-width: 768px)`,
    mdMax: `(max-width: 991px)`,
    lg: `(min-width: 992px)`,
    xl: `(min-width: 1200px)`,
    xxl: `(min-width: 1440px)`,
    XXXL: `(min-width: 1680px)`,
    XXXXL: `(min-width: 1920px)`,
  },
  color: {
    darkTeal: "#1b7c89",
    lightCyan: "#3ea5b3",
    sunset: "#F2C57C",
    buff: "#DDAE7E",
    darkSlate: "#283D3B",
    caribbeanCurrent: "#197278",
    champagePink: "#EDDDD4",
    eggplant: "#734B5E",
    caputMortuum: "#522A27",
  },
  fonts: {
    robotoRegular: "'robotoRegular', sans-serif",
    robotoItalic: "'robotoItalic', sans-serif",
  },
};
